### ISSUE TITLE
Update the Ubuntu Wiki....

### ISSUE THREAD

**Issue by roadapathy** [infogulch/pyspades#294]
Hey all! I have never gotten Pyspades to work. PIL won't install and the server will not run. Could we get an update on Ubuntu in order to help people get it working? I run Xubuntu 16.10, but if it works on 16.04 we should be up to date.

I feel like the code has changed since the WIKI was written. 

joel@zazzy:~/src/games/pyspades$ sh run_server.sh 
Traceback (most recent call last):
  File "run.py", line 87, in <module>
    from pyspades.server import (ServerProtocol, ServerConnection, position_data,
  File "../pyspades/server.py", line 20, in <module>
    from pyspades.protocol import BaseConnection, BaseProtocol
  File "../pyspades/protocol.py", line 19, in <module>
    from pyspades.bytes import ByteReader, ByteWriter
ImportError: No module named bytes

![screenshot_2017-01-17_16-00-00](https://cloud.githubusercontent.com/assets/6241235/22039682/3f06b1c0-dcce-11e6-9d52-69fb3ccc32fe.png)

**Comment by feikname** [comment]
@roadapathy You could try running [piqueserver](https://github.com/piqueserver/piqueserver/releases/tag/0.0.1). The alpha 0.0.1 runs just fine and there are almost no differences between it and pysnip server, which is similar to pyspades.

The build proccess of piqueserver is simplified, and there is an official pip package for easy installing. There is also an `-d` flag for changing the configuration directory and the wiki is updated.

**Note:** pyspades latest commit was more than 4 years ago, you should at minimum probably be using [PySnip](https://github.com/NateShoffner/PySnip) instead.

**EDIT:** The instructions I provided wouldn't work with pyspades, oops!
**EDIT 2:** Fix wrong information
**EDIT 3:** Add the note.

**Comment by feikname** [comment]
If you really want to just run pyspades and not PySnip or piqueserver, I will have a look into it right now. For the sake of correct information.

**Comment by feikname** [comment]
Sorry, I couldn't get it running :disappointed: 

With my very limited knowledge of Cython, I tried to compile `bytes.pyx` manually. However, it just kept accusing that 'readFloat()' was not defined as described in `bytes.pxd`. I checked it thrice and couldn't find the problem.

**Comment by roadapathy** [comment]
Supposedly this works but I haven't yet tried it!

https://github.com/piqueserver/piqueserver
